services:
  api:
    container_name: go-pg-api
    build:
      context: .
      dockerfile: ./docker/local/go/Dockerfile
    command: air -c .air.toml
    volumes:
      - ./src:/go/src
    ports:
      - "8080:8080"
    env_file:
      - .env
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    container_name: go-pg-db
    build:
      context: .
      dockerfile: ./docker/local/db/Dockerfile
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
      # ローカル環境でもパスワードを有効化する設定
      POSTGRES_INITDB_ARGS: --auth-local=scram-sha-256 --auth-host=scram-sha-256
    volumes:
      - db-data:/var/lib/postgresql
      # 初回起動時にSQLを実行する設定
      # - ./docker/local/db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file:
      - .env
volumes:
  db-data: